### ISSUE TITLE
source tracking commands crashing with "unable to generate complete component set for"

### ISSUE THREAD

**Issue by azlam-abdulsalam** [salesforcecli/plugin-source#279]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.   Check out a mpd repo with multiple packages of a medium size project
2.  Utilize sfdx force:source:beta:push -u <org>
2.  Notice the command generates an error  ```ERROR running force:source:beta:push:  unable to generate complete component set for ```

### Expected result

The command will be able to successfully push all metadata into the org

### Actual result

The command fails to execute push/pull 

### Additional information

Adding log levels provide with no additional context.

**VS Code Version**:

**SFDX CLI Version**:
7.125.0

**OS and version**:
Mac OS

**Comment by WillieRuemmele** [comment]
closing this issue, will track in the "issues only" repo
